---
# DATA INPUT PARAMETERS
#config_id: '23_026_vox_len_0.25m' # (str) - unique identifier for this configuration, used for voxel space identification (use same in config 2)
#working_dir: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/processed/23_026/voxrs' # (str) - working directory for intermediate and output files (use same in config 2)

#las_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/pointclouds_stripalign_clipmerge/23_026/23_026_clip_merge.las' # (str) - complete path to input .las file
#traj_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/metadata/drone_trajectory/snow_on_23_027_073_all_lidar_trajectory.txt' # (str)

# SNOW ON TEMPLATE
config_id: '23_027_073_snow_on_vox_len_0.25m' # (str) - unique identifier for this configuration, used for voxel space identification (use same in config 2)
working_dir: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/processed/snow-on/voxrs' # (str) - working directory for intermediate and output files (use same in config 2)

las_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/pointclouds_stripalign_clipmerge_snow_on_off/23_027_073_snow_on_merge.las' # (str) - complete path to input .las file
traj_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/metadata/drone_trajectory/snow_on_23_027_073_all_lidar_trajectory.txt' # (str)

# SNOW OFF TEMPLATE
#config_id: '23_026_072_snow_off_vox_len_0.25m' # (str) - unique identifier for this configuration, used for voxel space identification (use same in config 2)
#working_dir: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/processed/snow-off/voxrs' # (str) - working directory for intermediate and output files (use same in config 2)

#las_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/pointclouds_stripalign_clipmerge_snow_on_off/23_026_072_snow_off_merge.las' # (str) - complete path to input .las file
#traj_in: '/globalhome/zvd094/HPC/sym_link_gwf_prj/fortress/lidar-processing/data/metadata/drone_trajectory/snow_off_23_026_072_all_lidar_trajectory.txt' # (str) - complete path to trajectory file (.csv) corresponding to las file.
          # trajectory file must include the following header labels: Time[s], Easting[m], Northing[m], Height[m]
          # make sure the time units in the las file and traj file are the same. Standard GPS time is better than GPS seconds of the week. 

return_set: "first"  # (str) - .las returns to be considered in sampling ('first' [recommended], 'last', or 'all')
drop_class: 31 # (int) single class to be dropped from .las file prior to interpolation (blank or -1 for none)

# VOXEL SPACE PARAMETERS
cw_rotation_deg: 0  # (int) rotation of primary voxelspace axis in degrees (default 0)
voxel_length: 0.25  # cubic voxel dimension in meters

# PROCESSING PARAMETERS
las_traj_chunksize: 5000000  # (int) point cloud chunk size for interpolation with trajectory (default 10000000, decrease for memory management)
z_slices: 32  # (int) - number of horizontal layers for chunking of ray sampling (default 4, increase for memory management)
